name: Build IaC Stack

on:
  - workflow_dispatch
  - push

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: '[ACTION] | Clone build iac action'
        uses: actions/checkout@v3
        with:
          repository: heronlabs/build-iac-action
          ref: 2.0.0
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS}}
          path: ./build-iac-action

      - name: '[ACTION] | Run build iac action'
        uses: './build-iac-action/application/github'
